import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/app/provider';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import Script from 'next/script';
import SetScreenHeight from '@/components/layouts/SetScreenHeight';

const SuitMedium = localFont({
  src: '../../public/assets/fonts/SUIT-Medium.otf',
  variable: '--font-suit',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${SuitMedium.variable} antialiased flex flex-col min-h-[calc(var(--vh)_*_100)] w-full`}>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_KAKAOAPP_KEY}&libraries=services&autoload=false`}
          strategy='beforeInteractive'
        />
        <SetScreenHeight />
        <Providers>
          <Header />
          <main className='h-full w-full flex-1'>{children}</main>
          <div id='modal'></div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
