import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/app/provider';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import Script from 'next/script';
import SetScreenHeight from '@/components/layouts/SetScreenHeight';
import { ReviewBottomSheetProvider } from '@/provider/reviewBottomSheetProvider';

const SUIT = localFont({
  src: '../../public/assets/fonts/SUIT-Variable.ttf',
  variable: '--font-suit',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximun-scale=1.0, user-scalable=no'
        />
      </head>
      <body
        className={`${SUIT.variable} font-main antialiased flex flex-col min-h-[calc(var(--vh)_*_100)] max-w-full overflow-x-hidden`}
      >
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_KAKAOAPP_KEY}&libraries=services&autoload=false`}
          strategy='beforeInteractive'
        />
        <SetScreenHeight />
        <Providers>
          <ReviewBottomSheetProvider isReviewBottomSheetOpen={false}>
            <Header />
            <main className='h-full max-w-full flex-1'>{children}</main>
            <div id='modal'></div>
            <Footer />
          </ReviewBottomSheetProvider>
        </Providers>
      </body>
    </html>
  );
}
